# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db14b3e50c4d1755657d320a7f92d8d38a983db2ecfeb72ac444692d892d8a9cc9d46e83127899b4ac79dacb6d3e5a23517357a5b8f00c9b0b2b85624ce17d0

test:
  secret_key_base: 78012dd33c8c16b636672ecb0b0b3b0719d79bc579a68b75f155477f937de24bde04cdfbeb9bc5a56864be0b6be1981c10cedc720596ee25eb5f1ce5fb930aed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
